// <auto-generated />
using System;
using BookingVerseFinalAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingVerseFinalAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BookingVerseFinalAPI.Model.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "admin1@example.com",
                            FirstName = "Hans",
                            LastName = "Mueller",
                            Password = "admin123"
                        },
                        new
                        {
                            ID = 2,
                            Email = "user1@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "user123"
                        });
                });

            modelBuilder.Entity("BookingVerseFinalAPI.Model.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Category 1",
                            Date = new DateTime(2024, 6, 16, 14, 57, 13, 379, DateTimeKind.Local).AddTicks(4707),
                            Description = "Description 1",
                            Location = "Location 1",
                            Price = 50.0m,
                            Title = "Event 1"
                        },
                        new
                        {
                            ID = 2,
                            Category = "Category 2",
                            Date = new DateTime(2024, 6, 16, 14, 57, 13, 379, DateTimeKind.Local).AddTicks(4789),
                            Description = "Description 2",
                            Location = "Location 2",
                            Price = 75.0m,
                            Title = "Event 2"
                        });
                });

            modelBuilder.Entity("BookingVerseFinalAPI.Model.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("EventID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BookingVerseFinalAPI.Model.Order", b =>
                {
                    b.HasOne("BookingVerseFinalAPI.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingVerseFinalAPI.Model.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
